/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_DEMO_DEMO_PB_H_INCLUDED
#define PB_DEMO_DEMO_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/timestamp.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Application level version validation */
typedef enum demo_version {
    DEMO_VERSION_UNSPECIFIED = 0,
    DEMO_VERSION_CURRENT = 1
} demo_version_t;

typedef enum demo_action { /* first entry in enum should ALWAYS be zero, in order to give clear distinction of EMPTY data in the message
 Eg. if zero is valid entry - unknown if the data is to be ignored or used */
    /* From the protobuf guide
 "There must be a zero value, so that we can use 0 as a numeric default value."
 "The zero value needs to be the first element, for compatibility with the proto2 semantics where the first enum value is always the default." */
    DEMO_ACTION_UNSPECIFIED = 0,
    DEMO_ACTION_SYNC_TIME = 1,
    DEMO_ACTION_SOFT_RESET = 2
} demo_action_t;

/* Struct definitions */
typedef struct demo_datapoint {
    uint16_t datapoint_tid;
    pb_byte_t data[16];
} demo_datapoint_t;

typedef struct demo_error_data {
    uint32_t code;
    char msg[16];
} demo_error_data_t;

typedef struct demo_get_datapoint_request {
    pb_size_t datapoint_tid_count;
    uint16_t datapoint_tid[4];
} demo_get_datapoint_request_t;

typedef struct demo_get_datapoint_response {
    pb_size_t datapoints_count;
    demo_datapoint_t datapoints[4];
} demo_get_datapoint_response_t;

typedef struct demo_get_time_request {
    /* Empty messages need a dummy variable for struct generation */
    uint32_t dummy;
} demo_get_time_request_t;

typedef struct demo_get_time_response {
    bool has_system_time;
    google_protobuf_timestamp_t system_time;
} demo_get_time_response_t;

typedef struct demo_execute_action_request {
    demo_action_t action;
} demo_execute_action_request_t;

typedef struct demo_execute_action_response {
    uint32_t dummy;
} demo_execute_action_response_t;

/* From Host -> Machine */
typedef struct demo_request {
    demo_version_t version;
    /* Note that all ints are 32bit - 8 and 16 are defined by using '.options' */
    uint16_t ref_id;
    pb_size_t which_type;
    union {
        demo_get_datapoint_request_t get_datapoint;
        demo_get_time_request_t get_time;
        demo_execute_action_request_t execute_action;
    } type;
} demo_request_t;

/* From Machine -> Host */
typedef struct demo_response {
    demo_version_t version;
    uint16_t ref_id;
    bool has_error;
    demo_error_data_t error;
    pb_size_t which_type;
    union {
        /* Note that ids do not need to match their 'Request' counterparts */
        demo_get_datapoint_response_t get_datapoint;
        demo_get_time_response_t get_time;
        demo_execute_action_response_t execute_action;
    } type;
} demo_response_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _DEMO_VERSION_MIN DEMO_VERSION_UNSPECIFIED
#define _DEMO_VERSION_MAX DEMO_VERSION_CURRENT
#define _DEMO_VERSION_ARRAYSIZE ((demo_version_t)(DEMO_VERSION_CURRENT+1))
#define demo_Version_VERSION_UNSPECIFIED demo_VERSION_UNSPECIFIED
#define demo_Version_VERSION_CURRENT demo_VERSION_CURRENT

#define _DEMO_ACTION_MIN DEMO_ACTION_UNSPECIFIED
#define _DEMO_ACTION_MAX DEMO_ACTION_SOFT_RESET
#define _DEMO_ACTION_ARRAYSIZE ((demo_action_t)(DEMO_ACTION_SOFT_RESET+1))
#define demo_Action_ACTION_UNSPECIFIED demo_ACTION_UNSPECIFIED
#define demo_Action_ACTION_SYNC_TIME demo_ACTION_SYNC_TIME
#define demo_Action_ACTION_SOFT_RESET demo_ACTION_SOFT_RESET







#define demo_execute_action_request_t_action_ENUMTYPE demo_action_t


#define demo_request_t_version_ENUMTYPE demo_version_t

#define demo_response_t_version_ENUMTYPE demo_version_t


/* Initializer values for message structs */
#define DEMO_DATAPOINT_INIT_DEFAULT              {0, {0}}
#define DEMO_ERROR_DATA_INIT_DEFAULT             {0, ""}
#define DEMO_GET_DATAPOINT_REQUEST_INIT_DEFAULT  {0, {0, 0, 0, 0}}
#define DEMO_GET_DATAPOINT_RESPONSE_INIT_DEFAULT {0, {DEMO_DATAPOINT_INIT_DEFAULT, DEMO_DATAPOINT_INIT_DEFAULT, DEMO_DATAPOINT_INIT_DEFAULT, DEMO_DATAPOINT_INIT_DEFAULT}}
#define DEMO_GET_TIME_REQUEST_INIT_DEFAULT       {0}
#define DEMO_GET_TIME_RESPONSE_INIT_DEFAULT      {false, GOOGLE_PROTOBUF_TIMESTAMP_INIT_DEFAULT}
#define DEMO_EXECUTE_ACTION_REQUEST_INIT_DEFAULT {_DEMO_ACTION_MIN}
#define DEMO_EXECUTE_ACTION_RESPONSE_INIT_DEFAULT {0}
#define DEMO_REQUEST_INIT_DEFAULT                {_DEMO_VERSION_MIN, 0, 0, {DEMO_GET_DATAPOINT_REQUEST_INIT_DEFAULT}}
#define DEMO_RESPONSE_INIT_DEFAULT               {_DEMO_VERSION_MIN, 0, false, DEMO_ERROR_DATA_INIT_DEFAULT, 0, {DEMO_GET_DATAPOINT_RESPONSE_INIT_DEFAULT}}
#define DEMO_DATAPOINT_INIT_ZERO                 {0, {0}}
#define DEMO_ERROR_DATA_INIT_ZERO                {0, ""}
#define DEMO_GET_DATAPOINT_REQUEST_INIT_ZERO     {0, {0, 0, 0, 0}}
#define DEMO_GET_DATAPOINT_RESPONSE_INIT_ZERO    {0, {DEMO_DATAPOINT_INIT_ZERO, DEMO_DATAPOINT_INIT_ZERO, DEMO_DATAPOINT_INIT_ZERO, DEMO_DATAPOINT_INIT_ZERO}}
#define DEMO_GET_TIME_REQUEST_INIT_ZERO          {0}
#define DEMO_GET_TIME_RESPONSE_INIT_ZERO         {false, GOOGLE_PROTOBUF_TIMESTAMP_INIT_ZERO}
#define DEMO_EXECUTE_ACTION_REQUEST_INIT_ZERO    {_DEMO_ACTION_MIN}
#define DEMO_EXECUTE_ACTION_RESPONSE_INIT_ZERO   {0}
#define DEMO_REQUEST_INIT_ZERO                   {_DEMO_VERSION_MIN, 0, 0, {DEMO_GET_DATAPOINT_REQUEST_INIT_ZERO}}
#define DEMO_RESPONSE_INIT_ZERO                  {_DEMO_VERSION_MIN, 0, false, DEMO_ERROR_DATA_INIT_ZERO, 0, {DEMO_GET_DATAPOINT_RESPONSE_INIT_ZERO}}

/* Field tags (for use in manual encoding/decoding) */
#define DEMO_DATAPOINT_DATAPOINT_TID_TAG         1
#define DEMO_DATAPOINT_DATA_TAG                  2
#define DEMO_ERROR_DATA_CODE_TAG                 1
#define DEMO_ERROR_DATA_MSG_TAG                  2
#define DEMO_GET_DATAPOINT_REQUEST_DATAPOINT_TID_TAG 1
#define DEMO_GET_DATAPOINT_RESPONSE_DATAPOINTS_TAG 1
#define DEMO_GET_TIME_REQUEST_DUMMY_TAG          1
#define DEMO_GET_TIME_RESPONSE_SYSTEM_TIME_TAG   1
#define DEMO_EXECUTE_ACTION_REQUEST_ACTION_TAG   1
#define DEMO_EXECUTE_ACTION_RESPONSE_DUMMY_TAG   1
#define DEMO_REQUEST_VERSION_TAG                 1
#define DEMO_REQUEST_REF_ID_TAG                  2
#define DEMO_REQUEST_GET_DATAPOINT_TAG           3
#define DEMO_REQUEST_GET_TIME_TAG                4
#define DEMO_REQUEST_EXECUTE_ACTION_TAG          5
#define DEMO_RESPONSE_VERSION_TAG                1
#define DEMO_RESPONSE_REF_ID_TAG                 2
#define DEMO_RESPONSE_ERROR_TAG                  3
#define DEMO_RESPONSE_GET_DATAPOINT_TAG          4
#define DEMO_RESPONSE_GET_TIME_TAG               5
#define DEMO_RESPONSE_EXECUTE_ACTION_TAG         6

/* Struct field encoding specification for nanopb */
#define DEMO_DATAPOINT_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   datapoint_tid,     1) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, data,              2)
#define DEMO_DATAPOINT_CALLBACK NULL
#define DEMO_DATAPOINT_DEFAULT NULL

#define DEMO_ERROR_DATA_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   code,              1) \
X(a, STATIC,   SINGULAR, STRING,   msg,               2)
#define DEMO_ERROR_DATA_CALLBACK NULL
#define DEMO_ERROR_DATA_DEFAULT NULL

#define DEMO_GET_DATAPOINT_REQUEST_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, UINT32,   datapoint_tid,     1)
#define DEMO_GET_DATAPOINT_REQUEST_CALLBACK NULL
#define DEMO_GET_DATAPOINT_REQUEST_DEFAULT NULL

#define DEMO_GET_DATAPOINT_RESPONSE_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  datapoints,        1)
#define DEMO_GET_DATAPOINT_RESPONSE_CALLBACK NULL
#define DEMO_GET_DATAPOINT_RESPONSE_DEFAULT NULL
#define demo_get_datapoint_response_t_datapoints_MSGTYPE demo_datapoint_t

#define DEMO_GET_TIME_REQUEST_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define DEMO_GET_TIME_REQUEST_CALLBACK NULL
#define DEMO_GET_TIME_REQUEST_DEFAULT NULL

#define DEMO_GET_TIME_RESPONSE_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  system_time,       1)
#define DEMO_GET_TIME_RESPONSE_CALLBACK NULL
#define DEMO_GET_TIME_RESPONSE_DEFAULT NULL
#define demo_get_time_response_t_system_time_MSGTYPE google_protobuf_timestamp_t

#define DEMO_EXECUTE_ACTION_REQUEST_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    action,            1)
#define DEMO_EXECUTE_ACTION_REQUEST_CALLBACK NULL
#define DEMO_EXECUTE_ACTION_REQUEST_DEFAULT NULL

#define DEMO_EXECUTE_ACTION_RESPONSE_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   dummy,             1)
#define DEMO_EXECUTE_ACTION_RESPONSE_CALLBACK NULL
#define DEMO_EXECUTE_ACTION_RESPONSE_DEFAULT NULL

#define DEMO_REQUEST_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    version,           1) \
X(a, STATIC,   SINGULAR, UINT32,   ref_id,            2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,get_datapoint,type.get_datapoint),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,get_time,type.get_time),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,execute_action,type.execute_action),   5)
#define DEMO_REQUEST_CALLBACK NULL
#define DEMO_REQUEST_DEFAULT NULL
#define demo_request_t_type_get_datapoint_MSGTYPE demo_get_datapoint_request_t
#define demo_request_t_type_get_time_MSGTYPE demo_get_time_request_t
#define demo_request_t_type_execute_action_MSGTYPE demo_execute_action_request_t

#define DEMO_RESPONSE_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    version,           1) \
X(a, STATIC,   SINGULAR, UINT32,   ref_id,            2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  error,             3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,get_datapoint,type.get_datapoint),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,get_time,type.get_time),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,execute_action,type.execute_action),   6)
#define DEMO_RESPONSE_CALLBACK NULL
#define DEMO_RESPONSE_DEFAULT NULL
#define demo_response_t_error_MSGTYPE demo_error_data_t
#define demo_response_t_type_get_datapoint_MSGTYPE demo_get_datapoint_response_t
#define demo_response_t_type_get_time_MSGTYPE demo_get_time_response_t
#define demo_response_t_type_execute_action_MSGTYPE demo_execute_action_response_t

extern const pb_msgdesc_t demo_datapoint_t_msg;
extern const pb_msgdesc_t demo_error_data_t_msg;
extern const pb_msgdesc_t demo_get_datapoint_request_t_msg;
extern const pb_msgdesc_t demo_get_datapoint_response_t_msg;
extern const pb_msgdesc_t demo_get_time_request_t_msg;
extern const pb_msgdesc_t demo_get_time_response_t_msg;
extern const pb_msgdesc_t demo_execute_action_request_t_msg;
extern const pb_msgdesc_t demo_execute_action_response_t_msg;
extern const pb_msgdesc_t demo_request_t_msg;
extern const pb_msgdesc_t demo_response_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DEMO_DATAPOINT_FIELDS &demo_datapoint_t_msg
#define DEMO_ERROR_DATA_FIELDS &demo_error_data_t_msg
#define DEMO_GET_DATAPOINT_REQUEST_FIELDS &demo_get_datapoint_request_t_msg
#define DEMO_GET_DATAPOINT_RESPONSE_FIELDS &demo_get_datapoint_response_t_msg
#define DEMO_GET_TIME_REQUEST_FIELDS &demo_get_time_request_t_msg
#define DEMO_GET_TIME_RESPONSE_FIELDS &demo_get_time_response_t_msg
#define DEMO_EXECUTE_ACTION_REQUEST_FIELDS &demo_execute_action_request_t_msg
#define DEMO_EXECUTE_ACTION_RESPONSE_FIELDS &demo_execute_action_response_t_msg
#define DEMO_REQUEST_FIELDS &demo_request_t_msg
#define DEMO_RESPONSE_FIELDS &demo_response_t_msg

/* Maximum encoded size of messages (where known) */
#define DEMO_DATAPOINT_SIZE                      22
#define DEMO_ERROR_DATA_SIZE                     23
#define DEMO_EXECUTE_ACTION_REQUEST_SIZE         2
#define DEMO_EXECUTE_ACTION_RESPONSE_SIZE        6
#define DEMO_GET_DATAPOINT_REQUEST_SIZE          16
#define DEMO_GET_DATAPOINT_RESPONSE_SIZE         96
#define DEMO_GET_TIME_REQUEST_SIZE               6
#define DEMO_GET_TIME_RESPONSE_SIZE              24
#define DEMO_REQUEST_SIZE                        24
#define DEMO_RESPONSE_SIZE                       129

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
