/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "demo.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(DEMO_DATAPOINT, demo_datapoint_t, AUTO)


PB_BIND(DEMO_ERROR_DATA, demo_error_data_t, AUTO)


PB_BIND(DEMO_GET_DATAPOINT_REQUEST, demo_get_datapoint_request_t, AUTO)


PB_BIND(DEMO_GET_DATAPOINT_RESPONSE, demo_get_datapoint_response_t, AUTO)


PB_BIND(DEMO_GET_TIME_REQUEST, demo_get_time_request_t, AUTO)


PB_BIND(DEMO_GET_TIME_RESPONSE, demo_get_time_response_t, AUTO)


PB_BIND(DEMO_EXECUTE_ACTION_REQUEST, demo_execute_action_request_t, AUTO)


PB_BIND(DEMO_EXECUTE_ACTION_RESPONSE, demo_execute_action_response_t, AUTO)


PB_BIND(DEMO_REQUEST, demo_request_t, AUTO)


PB_BIND(DEMO_RESPONSE, demo_response_t, AUTO)





